
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'crafting_misc_more_dyed_wool_and_carpet', version = '5.6+mod', displayName = 'More Dyed Wool And Carpet', description = 'Craft 8 Wool Or Carpet Instead Of One At A Time', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/z9M75QAX/forge_updates.json?neoforge=only', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-more-dyed-wool-and-carpet' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
