modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
    { modId = 'effective_tools_pickaxe_glass', version = '3.6+mod', displayName = 'Pickaxe Glass', description = 'Glass Breaks Faster With A Pickaxe', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/y87pO5HP/forge_updates.json', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-pickaxe-effective-glass' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
