modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
    { modId = 'crafting_re_dye_glass', version = '4.6+mod', displayName = 'Glass', description = 'Re-Dye All Colors Of Glass', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/sbHA4Z4I/forge_updates.json', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-re-dye-glass' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
