modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
    { modId = 'effective_tools_pickaxe_reinforced_deepslate', version = '3.6+mod', displayName = 'Pickaxe Reinforced Deepslate', description = 'Reinforced Deepslate Breaks Faster With A Pickaxe', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/kbuqezYO/forge_updates.json', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-pickaxe-effective-reinforced-deepslate' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
