
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'crafting_smelting_blasting_smelts_glass', version = '4.6+mod', displayName = 'Blasting Smelts Glass', description = 'Blasting Furnace Smelts Glass', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/yQr7wOEY/forge_updates.json?neoforge=only', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpack-blasting-smelts-glass' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
