
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'world_behavior_four_new_paintings_are_placeable', version = '3.6+mod', displayName = 'Four New Paintings Are Placeable', description = 'The Four New Paintings Are Placeable', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/UDhPA1TM/forge_updates.json?neoforge=only', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-placeable-new-paintings' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
