
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'effective_tools_axe_skulls', version = '3.6+mod', displayName = 'Axe Effective For Skulls', description = 'Skulls And Heads Break Faster With An Axe', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/S7cHoMDR/forge_updates.json?neoforge=only', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-axe-effective-skulls' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
