modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
    { modId = 'crafting_misc_one_step_dyed_shulker_boxes', version = '4.6+mod', displayName = 'One Step Dyed Shulker Boxes', description = 'Craft Dyed Shulkers From Scratch', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/cNHq7t9M/forge_updates.json', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-one-step-dyed-shulker-boxes' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
