
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'crafting_smithing_tools_netherite_no_template', version = '4.6+mod', displayName = 'Netherite No Template', description = 'Upgrade Diamond Tools to Netherite Without A Template', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/R1WCIhLq/forge_updates.json?neoforge=only', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-no-template-netherite-tool-upgrades' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
