modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
    { modId = 'effective_tools_hoe_cactus', version = '3.6+mod', displayName = 'Hoe Effective For Cactus', description = 'Cactus Breaks Faster With A Hoe', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/Xqq7IBeE/forge_updates.json', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-hoe-effective-cactus' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
