modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
    { modId = 'crafting_smithing_tools_iron_to_diamond', version = '4.6+mod', displayName = 'Upgrade Iron Tools To Diamond', description = 'Upgrade Iron Tools To Diamond Ones', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/fOi8LwAw/forge_updates.json', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-iron-to-diamond-tools-upgrades' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
