
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'effective_tools_hoe_froglights', version = '3.6+mod', displayName = 'Hoe Froglights', description = 'Froglights Break Faster Using A Hoe', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/dpLYDTiH/forge_updates.json?neoforge=only', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-hoe-effective-froglights' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
