modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
    { modId = 'crafting_stonecutting_wood_slabs_and_stairs', version = '1.7+mod', displayName = 'Slabs And Stairs', description = 'Use the stonecutter to get stairs, slabs, fences, and fence gates from planks', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/k4swAzko/forge_updates.json', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-stonecutter-cuts-slabs' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
