
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'beacon_base_lapis', version = '3.6+mod', displayName = 'Lapis Beacons', description = 'Lapis Blocks Can Be Used As A Beacon Base. Lapis Lazuli Can Be Used As A Beacon Payment Item', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/gDqoouES/forge_updates.json?neoforge=only', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-lapis-beacon-base' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
