
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'crafting_re_dye_terracotta', version = '4.6+mod', displayName = 'Terracotta', description = 'Re-Dye All Colors Of Terracotta', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/lANiwxxT/forge_updates.json?neoforge=only', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-re-dye-terracotta' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
