
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'crafting_smithing_tools_stone_to_iron', version = '4.6+mod', displayName = 'Upgrade Stone Tools To Iron', description = 'Upgrade Stone Tools To Iron Ones', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/8zLmjJ4K/forge_updates.json?neoforge=only', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-stone-to-iron-tools-upgrades' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
