modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
    { modId = 'beacon_base_amethyst', version = '3.8+mod', displayName = 'Amethyst Beacons', description = 'Amethyst Blocks Can Be Used As A Beacon Base. Amethyst Shards Can Be Used As A Beacon Payment Item.', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/EP4tesbZ/forge_updates.json', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpacks-amethyst-beacon-base' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
