modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
    { modId = 'mobs_behavior_axolotl_ignore_passives', version = '3.6+mod', displayName = 'Axolotl Ignore Passives', description = 'Axolotls Do Not Attack Passive Mobs', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/uqr5V1OT/forge_updates.json', credits = 'By PurpurMC', authors = ["granny", "Rhythmic", "PurpurMC"], displayURL = 'https://modrinth.com/mod/purpurpack-axolotls-ignore-passives' },
]
issueTrackerURL = 'https://github.com/PurpurMC/PurpurPacks/issues'
